### ISSUE TITLE
include example in the readme (~1h)

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/quickfix-tradeclient-rabbitmq#1]
Let's write a small example showing how an order sent through a message to rabbitmq ends up in the tradeclient. Maybe include the example in the README. Also we need to clarify in the README that the purpose is that the tradeclient will forward the order received from rabbitmq to an executor. This is opposed to the demo tradeclient from the original repo that received an order from the user input on the command line and then forwarded it to the executor

**Comment by shadiakiki1986** [comment]
Your example shows sample messages, but doesn't include real commands that send the message. For example, look at the examples posted in [json-table](https://github.com/micha/json-table/#example-1)

**Comment by shadiakiki1986** [comment]
This seems to be fixed with the `rabbitmqadmin....` commands in the readme. Can you confirm to close this issue?

**Comment by MickMek** [comment]
yes, fixed
